name: Build

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x86]

    steps:
    - uses: actions/checkout@v4
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.configuration}} -A Win32
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.configuration}} --parallel
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{matrix.configuration}}
        path: ${{github.workspace}}/build/bin/${{ matrix.configuration == 'Debug' && 'debug' || 'release' }}

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Download Build Artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-Release
        path: release
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          release/*.exe
          release/*.dll
        draft: false
        prerelease: false 